//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tracker.Web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class trackerwebdbEntities2 : DbContext
    {
        public trackerwebdbEntities2()
            : base("name=trackerwebdbEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Inventory> Inventories { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<FullInventoryView> FullInventoryViews { get; set; }
        public virtual DbSet<SemiInventoryView> SemiInventoryViews { get; set; }
        public virtual DbSet<TryOnAtHomeView> TryOnAtHomeViews { get; set; }
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }
        public virtual DbSet<Tracking> Trackings { get; set; }
        public virtual DbSet<FullInventoryView2> FullInventoryView2 { get; set; }
        public virtual DbSet<UpdateInventoryLocation> UpdateInventoryLocations { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<TOAH_readyCount> TOAH_readyCount { get; set; }
        public virtual DbSet<ProductType> ProductTypes { get; set; }
        public virtual DbSet<TOAH_allOptions> TOAH_allOptions { get; set; }
        public virtual DbSet<TOAH_requests> TOAH_requests { get; set; }
        public virtual DbSet<TOAH_requests2> TOAH_requests2 { get; set; }
        public virtual DbSet<TOAH_requests3> TOAH_requests3 { get; set; }
        public virtual DbSet<TOAH_sizeRelevant8> TOAH_sizeRelevant8 { get; set; }
        public virtual DbSet<UnshippedTOAH> UnshippedTOAHs { get; set; }
        public virtual DbSet<SizingRule> SizingRules { get; set; }
    
        public virtual ObjectResult<InsertOrUpdateTracking_Result> InsertOrUpdateTracking(string trackingNumber, string status, string updateDate, string estDeliveryDate)
        {
            var trackingNumberParameter = trackingNumber != null ?
                new ObjectParameter("trackingNumber", trackingNumber) :
                new ObjectParameter("trackingNumber", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            var updateDateParameter = updateDate != null ?
                new ObjectParameter("updateDate", updateDate) :
                new ObjectParameter("updateDate", typeof(string));
    
            var estDeliveryDateParameter = estDeliveryDate != null ?
                new ObjectParameter("estDeliveryDate", estDeliveryDate) :
                new ObjectParameter("estDeliveryDate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<InsertOrUpdateTracking_Result>("InsertOrUpdateTracking", trackingNumberParameter, statusParameter, updateDateParameter, estDeliveryDateParameter);
        }
    }
}
