//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tracker.Web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class trackerwebdbEntities2 : DbContext
    {
        public trackerwebdbEntities2()
            : base("name=trackerwebdbEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Inventory> Inventories { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Tracking> Tracking { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<FullInventoryView> FullInventoryViews { get; set; }
        public virtual DbSet<SemiInventoryView> SemiInventoryViews { get; set; }
        public virtual DbSet<TryOnAtHomeView> TryOnAtHomeViews { get; set; }
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }
    }
}
