//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tracker.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SizingRule
    {
        public string ProductType { get; set; }
        public Nullable<int> Size { get; set; }
        public Nullable<int> LowerLimitAdjustment { get; set; }
        public Nullable<int> UpperLimitAdjustment { get; set; }
        public string SizingCode { get; set; }
    
        public virtual ProductType ProductType1 { get; set; }
    }
}
