//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tracker.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOAH_readyCount
    {
        public int OrderId { get; set; }
        public Nullable<int> ShipableCount { get; set; }
        public Nullable<long> RequestCount { get; set; }
        public int ReadyToShip { get; set; }
    }
}
