//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tracker.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOAH_sizeRelevant
    {
        public string Type { get; set; }
        public string Request_RequestedItem { get; set; }
        public Nullable<int> Request_StreetSize { get; set; }
        public int OrderId { get; set; }
        public string Name { get; set; }
        public string SKU { get; set; }
        public Nullable<int> InventoryId { get; set; }
        public Nullable<int> Size { get; set; }
        public string Location { get; set; }
        public Nullable<int> LowerLimitAdjustment { get; set; }
        public Nullable<int> UpperLimitAdjustment { get; set; }
        public Nullable<int> SizeDiff { get; set; }
    }
}
