//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tracker.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UpdateInventoryLocation
    {
        public int InventoryId { get; set; }
        public string SKU { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public Nullable<int> Size { get; set; }
        public string Color { get; set; }
        public string Extras { get; set; }
        public string Location { get; set; }
        public string status { get; set; }
        public string estDeliveryDate { get; set; }
        public string trackingNumber { get; set; }
        public Nullable<bool> isReturnLabel { get; set; }
    }
}
